name: Build HandBrakeCLI Binaries

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - tools/config.json
      - tools/HandBrakeCLI/manifest.json

permissions:
  contents: write

jobs:
  build_HandBrakeCLI_alpine:
    name: Build HandBrakeCLI on Alpine
    uses: ./.github/workflows/build-bin.yml
    with:
      toolName: HandBrakeCLI
      osName: alpine-3.19
    secrets: inherit

  build_HandBrakeCLI_ubuntu:
    name: Build HandBrakeCLI on Ubuntu
    uses: ./.github/workflows/build-bin.yml
    with:
      toolName: HandBrakeCLI
      osName: ubuntu-22.04
    secrets: inherit
