name: Update Tool Manifests

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"

jobs:
  updateToolManifests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          token: ${{secrets.PAT_MEDIA_TOOLS_BIN}}

      - name: Update manifest files
        env:
          GH_TOKEN: ${{secrets.PAT_MEDIA_TOOLS_BIN}}
        run: ./scripts/update-tool-manifests.sh
